# Site settings
title: Portfolio | Pierre CHALLES
description: Portfolio | Pierre CHALLES
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Pierre CHALLES
user_description: Hello, moi c'est Pierre CHALLESğŸ‘‹

Je suis actuellement Ã©tudiant au Centre de Formation 3iFA d'Alencon mais dÃ©localisÃ© Ã  l'Aigle ğŸ—ºï¸ en premiÃ¨re annÃ©e de BTS SIO (Services Informatiques aux Organisations) dans l'option SLAM (Solutions Logicielles et Application MÃ©tier) qui en gros est une option spÃ©cialisÃ©e pour le dÃ©veloppement ğŸ’»

Actuellement toujours en cours d'Ã©tude ğŸ“, je vous propose sur ce portfolio de retrouver ci-dessous les diffÃ©rentes Ã©tudes, et projet professionnel que j'ai pu entreprendre au sein de ma carriÃ¨re.

Vous retrouverez ci-dessous mon CV ainsi que mes diffÃ©rents projets ğŸ‘©â€ğŸ’»
user_title: Software Developer
email: pch@mtb111.fr

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
